schemaVersion: 2.2.0
metadata:
  name: redhat-vscode-desktop

components:
  - name: tools
    container:
      image: quay.io/devfile/universal-developer-image:ubi8-latest
      memoryRequest: 1G
      memoryLimit: 4G
      cpuRequest: '1'
      cpuLimit: '2'

commands:
  - id: install-dependencies
    exec:
      label: "Install dependencies"
      component: tools
      commandLine: "npm install"

  - id: build-vsix
    exec:
      label: "Build vsix binary"
      component: tools
      commandLine: "npm run build"
      group:
        kind: build
        isDefault: false
